#!/bin/bash
# LightCI Server — EC2 Deployment Script Template
# ================================================
# Generated by DeploymentAgent from .claude/templates/deploy-script.template.sh
#
# This template is instantiated with real values when the /deploy command is used.
# PLACEHOLDERS that must be replaced before use:
#   {{EC2_PUBLIC_IP}}    — Public IP of the EC2 instance
#   {{SSH_KEY_PATH}}     — Path to your .pem key file
#   {{DOCKER_USERNAME}}  — Docker Hub username
#   {{DOCKER_IMAGE}}     — Docker image name
#   {{DOCKER_TAG}}       — Docker image tag
#   {{APP_PORT}}         — Application port (default: 8080)
#   {{CONTAINER_NAME}}   — Docker container name on the host
#
# USAGE:
#   1. Set environment variables (see .claude/env/dev.env.example)
#   2. source .env
#   3. bash scripts/deploy.sh
#
# DO NOT EXECUTE via Claude — review and run manually.

set -euo pipefail

# ─── Configuration ────────────────────────────────────────────────────────────
# These values are either loaded from environment or can be set directly here.

EC2_PUBLIC_IP="${EC2_PUBLIC_IP:-{{EC2_PUBLIC_IP}}}"
SSH_KEY_PATH="${SSH_KEY_PATH:-{{SSH_KEY_PATH}}}"
DOCKER_USERNAME="${DOCKER_USERNAME:-{{DOCKER_USERNAME}}}"
DOCKER_IMAGE="${DOCKER_IMAGE:-{{DOCKER_IMAGE}}}"
DOCKER_TAG="${DOCKER_TAG:-{{DOCKER_TAG}}}"
APP_PORT="${APP_PORT:-{{APP_PORT}}}"
CONTAINER_NAME="${CONTAINER_NAME:-{{CONTAINER_NAME}}}"
SSH_USER="${SSH_USER:-ec2-user}"
IMAGE_REF="${DOCKER_USERNAME}/${DOCKER_IMAGE}:${DOCKER_TAG}"
HEALTH_CHECK_RETRIES=6
HEALTH_CHECK_INTERVAL=10

# ─── Pre-flight Checks ───────────────────────────────────────────────────────

echo "============================================"
echo " LightCI Server — EC2 Deployment"
echo " Target:    ${SSH_USER}@${EC2_PUBLIC_IP}"
echo " Image:     ${IMAGE_REF}"
echo " Port:      ${APP_PORT}"
echo " Container: ${CONTAINER_NAME}"
echo " Key:       ${SSH_KEY_PATH}"
echo "============================================"
echo ""

# Validate placeholder values were replaced
for PLACEHOLDER in "{{EC2_PUBLIC_IP}}" "{{SSH_KEY_PATH}}" "{{DOCKER_USERNAME}}" "{{DOCKER_IMAGE}}" "{{DOCKER_TAG}}"; do
  if echo "${EC2_PUBLIC_IP} ${SSH_KEY_PATH} ${DOCKER_USERNAME} ${DOCKER_IMAGE} ${DOCKER_TAG}" | grep -q "${PLACEHOLDER}"; then
    echo "ERROR: Template placeholder not replaced: ${PLACEHOLDER}"
    echo "Set the corresponding environment variable before running this script."
    exit 1
  fi
done

# Validate SSH key
if [ ! -f "${SSH_KEY_PATH}" ]; then
  echo "ERROR: SSH key not found: ${SSH_KEY_PATH}"
  exit 1
fi
chmod 400 "${SSH_KEY_PATH}"

# Test SSH connectivity
echo "[PRE-FLIGHT] Testing SSH connectivity..."
ssh -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    -o ConnectTimeout=15 \
    -o BatchMode=yes \
    "${SSH_USER}@${EC2_PUBLIC_IP}" \
    "echo 'SSH: OK'" || {
  echo "ERROR: Cannot connect to ${EC2_PUBLIC_IP} via SSH."
  echo "Check: EC2 instance is running, security group allows port 22."
  exit 1
}

# Verify Docker is available on EC2
echo "[PRE-FLIGHT] Checking Docker on EC2..."
ssh -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    "${SSH_USER}@${EC2_PUBLIC_IP}" \
    "docker --version" || {
  echo "ERROR: Docker not found on EC2."
  echo "Run first: bash scripts/docker-install.sh"
  exit 1
}

echo ""

# ─── Step 1: Authenticate to Registry ───────────────────────────────────────

echo "[1/5] Authenticating to Docker Hub on EC2..."
ssh -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    "${SSH_USER}@${EC2_PUBLIC_IP}" \
    "echo '${DOCKER_PASSWORD:-}' | docker login --username '${DOCKER_USERNAME}' --password-stdin 2>/dev/null || true"
# Note: DOCKER_PASSWORD is optional if the image is public.
# For private images, ensure DOCKER_PASSWORD is set in your environment.

# ─── Step 2: Pull Image ──────────────────────────────────────────────────────

echo "[2/5] Pulling Docker image: ${IMAGE_REF}"
ssh -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    "${SSH_USER}@${EC2_PUBLIC_IP}" \
    "docker pull '${IMAGE_REF}'"

# ─── Step 3: Stop and Remove Old Container ───────────────────────────────────

echo "[3/5] Stopping old container (if running)..."
ssh -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    "${SSH_USER}@${EC2_PUBLIC_IP}" << REMOTE_STOP
  docker stop '${CONTAINER_NAME}' 2>/dev/null && \
    echo "Stopped: ${CONTAINER_NAME}" || \
    echo "No running container named ${CONTAINER_NAME}"
  docker rm '${CONTAINER_NAME}' 2>/dev/null && \
    echo "Removed: ${CONTAINER_NAME}" || \
    echo "No container to remove"
REMOTE_STOP

# ─── Step 4: Run New Container ───────────────────────────────────────────────

echo "[4/5] Starting new container..."
ssh -i "${SSH_KEY_PATH}" \
    -o StrictHostKeyChecking=no \
    "${SSH_USER}@${EC2_PUBLIC_IP}" << REMOTE_RUN
  docker run -d \
    --name '${CONTAINER_NAME}' \
    --restart unless-stopped \
    -p '${APP_PORT}:${APP_PORT}' \
    -e SPRING_PROFILES_ACTIVE=prod \
    -e SERVER_PORT='${APP_PORT}' \
    --memory="512m" \
    --cpus="0.5" \
    '${IMAGE_REF}'
  echo "Container started: $(docker ps --filter name='${CONTAINER_NAME}' --format '{{.ID}}')"
REMOTE_RUN

# ─── Step 5: Health Check ────────────────────────────────────────────────────

echo "[5/5] Waiting for application to start..."
echo "(Will retry up to ${HEALTH_CHECK_RETRIES} times with ${HEALTH_CHECK_INTERVAL}s delay)"
echo ""

ATTEMPT=0
HTTP_STATUS="000"
while [ "${ATTEMPT}" -lt "${HEALTH_CHECK_RETRIES}" ]; do
  ATTEMPT=$((ATTEMPT + 1))
  echo "  Health check attempt ${ATTEMPT}/${HEALTH_CHECK_RETRIES}..."
  sleep "${HEALTH_CHECK_INTERVAL}"

  HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
    --max-time 10 \
    --connect-timeout 5 \
    "http://${EC2_PUBLIC_IP}:${APP_PORT}/actuator/health" 2>/dev/null || echo "000")

  if [ "${HTTP_STATUS}" = "200" ]; then
    break
  fi
  echo "  Got HTTP ${HTTP_STATUS} — not ready yet."
done

echo ""
if [ "${HTTP_STATUS}" = "200" ]; then
  echo "============================================"
  echo " DEPLOYMENT SUCCESS"
  echo ""
  echo " App URL:    http://${EC2_PUBLIC_IP}:${APP_PORT}"
  echo " Health URL: http://${EC2_PUBLIC_IP}:${APP_PORT}/actuator/health"
  echo " Image:      ${IMAGE_REF}"
  echo "============================================"
else
  echo "============================================"
  echo " DEPLOYMENT WARNING"
  echo " Health check did not return 200 after"
  echo " ${HEALTH_CHECK_RETRIES} attempts."
  echo " Last HTTP status: ${HTTP_STATUS}"
  echo ""
  echo " Container may still be starting."
  echo " Check logs:"
  echo "   ssh -i ${SSH_KEY_PATH} ${SSH_USER}@${EC2_PUBLIC_IP}"
  echo "   docker logs ${CONTAINER_NAME} --tail 50"
  echo "============================================"
fi
