# LightCI Server — Terraform EC2 Template
# =========================================
# Generated by AWSInfraAgent from .claude/templates/terraform-ec2.template.tf
#
# USAGE:
#   1. Copy to terraform/ (or use as-is if already there)
#   2. Replace TODO placeholders with actual values
#   3. Run: terraform init && terraform plan
#   4. Review the plan carefully
#   5. Run: terraform apply  (CREATES REAL AWS RESOURCES)
#
# COST WARNING:
#   This template creates real AWS resources that may incur charges.
#   Destroy when done: terraform destroy
#
# DO NOT COMMIT:
#   terraform.tfstate, terraform.tfstate.backup, *.tfvars (with real values)

# ─── Terraform Configuration ─────────────────────────────────────────────────

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  # TODO: For team environments, configure S3 backend for shared state.
  # Uncomment and fill in after creating the S3 bucket and DynamoDB table:
  #
  # backend "s3" {
  #   bucket         = "TODO: your-terraform-state-bucket-name"
  #   key            = "lightci/terraform.tfstate"
  #   region         = "TODO: your-aws-region"
  #   encrypt        = true
  #   dynamodb_table = "TODO: your-terraform-lock-table"
  # }
}

# ─── Provider ────────────────────────────────────────────────────────────────

provider "aws" {
  region  = var.region
  profile = var.aws_profile

  default_tags {
    tags = {
      Project     = "LightCI"
      ManagedBy   = "Terraform"
      Environment = var.environment
    }
  }
}

# ─── Data Sources ────────────────────────────────────────────────────────────

# Use the default VPC in the target region.
# TODO: Replace with a specific VPC if you are not using the default VPC.
data "aws_vpc" "default" {
  default = true
}

# Use the default subnet in availability zone "a" of the target region.
# TODO: Change availability_zone if the default subnet in "a" is unavailable.
data "aws_subnet" "default" {
  vpc_id            = data.aws_vpc.default.id
  default_for_az    = true
  availability_zone = "${var.region}a"
}

# Auto-select the latest Amazon Linux 2023 AMI for x86_64.
# This ensures the instance always uses a patched, up-to-date AMI.
# TODO: Pin to a specific AMI ID if reproducibility is required.
data "aws_ami" "amazon_linux_2023" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-2023.*-x86_64"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  filter {
    name   = "root-device-type"
    values = ["ebs"]
  }
}

# ─── Security Group ──────────────────────────────────────────────────────────

resource "aws_security_group" "lightci_sg" {
  name        = "lightci-server-sg-${var.environment}"
  description = "Security group for LightCI Server — ${var.environment}"
  vpc_id      = data.aws_vpc.default.id

  # SSH access
  # TODO (PRODUCTION): Replace 0.0.0.0/0 with your static IP or VPN CIDR.
  # Leaving SSH open to the world is acceptable for dev/demo but not production.
  ingress {
    description = "SSH access for administration"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    # TODO: Restrict to known IP: cidr_blocks = ["YOUR_IP/32"]
  }

  # Application port (LightCI web UI)
  ingress {
    description = "LightCI Server web UI"
    from_port   = var.app_port
    to_port     = var.app_port
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  # HTTPS (optional — enable when TLS is configured)
  # TODO: Uncomment this block when you add TLS/HTTPS support.
  # ingress {
  #   description = "HTTPS"
  #   from_port   = 443
  #   to_port     = 443
  #   protocol    = "tcp"
  #   cidr_blocks = ["0.0.0.0/0"]
  # }

  # All outbound traffic — required for: dnf update, docker pull, AWS API calls
  egress {
    description = "All outbound traffic"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    Name = "lightci-server-sg-${var.environment}"
  }
}

# ─── EC2 Instance ────────────────────────────────────────────────────────────

resource "aws_instance" "lightci_server" {
  ami                    = data.aws_ami.amazon_linux_2023.id
  instance_type          = var.instance_type

  # TODO: Ensure this key pair exists in your AWS account in the target region.
  key_name               = var.key_pair_name

  subnet_id                   = data.aws_subnet.default.id
  vpc_security_group_ids      = [aws_security_group.lightci_sg.id]
  associate_public_ip_address = true

  # IMDSv2 enforcement — prevents SSRF-based metadata theft
  metadata_options {
    http_endpoint               = "enabled"
    http_tokens                 = "required"   # IMDSv2 required
    http_put_response_hop_limit = 1
  }

  # Root EBS volume
  root_block_device {
    volume_size           = 20
    volume_type           = "gp3"
    delete_on_termination = true
    encrypted             = true
    # TODO: For production, add a KMS key:
    # kms_key_id = aws_kms_key.ebs.arn
  }

  # User data: runs once on first boot.
  # Installs Docker so the DeploymentAgent's deploy.sh can pull and run the container.
  # TODO: Replace with your own user_data if you need different bootstrap steps.
  user_data = base64encode(<<-EOF
    #!/bin/bash
    set -e
    exec > /var/log/user-data.log 2>&1

    echo "=== LightCI Server Bootstrap ==="
    echo "Started: $(date)"

    # Update packages
    dnf update -y

    # Install Docker
    dnf install -y docker

    # Enable and start Docker service
    systemctl enable docker
    systemctl start docker

    # Allow ec2-user to run Docker without sudo
    usermod -aG docker ec2-user

    # Install useful utilities
    dnf install -y curl wget jq

    echo "Bootstrap complete: $(date)"
    echo "Docker version: $(docker --version)"
    touch /tmp/bootstrap-complete
  EOF
  )

  tags = {
    Name = "lightci-server-${var.environment}"
  }
}

# ─── Variables ───────────────────────────────────────────────────────────────

variable "region" {
  description = "AWS region where resources will be created"
  type        = string
  default     = "us-east-1"
  # TODO: Change to your target region
}

variable "aws_profile" {
  description = "AWS CLI named profile for authentication"
  type        = string
  default     = "default"
  # TODO: Change to your AWS CLI profile name if not 'default'
}

variable "instance_type" {
  description = "EC2 instance type"
  type        = string
  default     = "t3.micro"
  # TODO: Upgrade to t3.small or t3.medium for production workloads
}

variable "key_pair_name" {
  description = "Name of the AWS EC2 key pair for SSH access (must already exist)"
  type        = string
  # TODO: Set via environment: export TF_VAR_key_pair_name=your-key-pair-name
  # Or pass on CLI:           terraform apply -var="key_pair_name=your-key"
}

variable "app_port" {
  description = "Application port to open in security group ingress"
  type        = number
  default     = 8080
}

variable "environment" {
  description = "Deployment environment label"
  type        = string
  default     = "dev"
  # TODO: Set to "prod" for production deployments
}

# ─── Outputs ─────────────────────────────────────────────────────────────────

output "instance_public_ip" {
  description = "Public IP of the LightCI Server EC2 instance — export as EC2_PUBLIC_IP"
  value       = aws_instance.lightci_server.public_ip
}

output "instance_id" {
  description = "EC2 instance ID — use in AWS console to manage the instance"
  value       = aws_instance.lightci_server.id
}

output "app_url" {
  description = "URL to access the LightCI Server web UI"
  value       = "http://${aws_instance.lightci_server.public_ip}:${var.app_port}"
}

output "health_url" {
  description = "Spring Boot Actuator health endpoint"
  value       = "http://${aws_instance.lightci_server.public_ip}:${var.app_port}/actuator/health"
}

output "ssh_command" {
  description = "SSH command to connect to the EC2 instance"
  value       = "ssh -i <YOUR_KEY.pem> ec2-user@${aws_instance.lightci_server.public_ip}"
}

output "security_group_id" {
  description = "Security group ID — use to add additional rules if needed"
  value       = aws_security_group.lightci_sg.id
}
